# Generated by Django 5.2 on 2025-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('author', models.CharField(max_length=30, verbose_name='author')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
