# Generated by Django 5.2 on 2025-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_az',
            field=models.CharField(max_length=30, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_az',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_tr',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_az',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
